name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run unit tests
      run: python -m unittest discover ${{github.workspace}}\test

    - name: Run parsing example smoke test
        run: python ${{github.workspace}}\examples\run_parsing_example.py -h

    - name: Run running example smoke test
        run: python ${{github.workspace}}\examples\run_running_example.py -h

  Linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run unit tests
      run: python3 -m unittest discover ${{github.workspace}}/test

    - name: Run parsing example smoke test
        run: python3 ${{github.workspace}}/examples/run_parsing_example.py -h

    - name: Run running example smoke test
        run: python3 ${{github.workspace}}/examples/run_running_example.py -h
