name: Windows tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run unit tests
      run: python -m unittest discover ${{github.workspace}}\test

    - name: Run smoke test for parsing example
      run: python ${{github.workspace}}\examples\run_parsing_example.py

    - name: Run smoke test for running example
      run: python ${{github.workspace}}\examples\run_running_example.py